// fb constants

// IMPORTANT NOTE PAGE_ID AND THE AUTH TOKEN WILL BE REPLACED BY CODE THAT CREATES LONG_TERM OAUTH TOKENS AND REFRESHES. FOR NOW THIS
const PAGE_ID = 718351648548456;
const AUTH_TOKEN =
  'EAAELyoAkOZC8BALRHzbplPpXdXTWm6qhLNwdiqOgnovzaCZBe6wOf02PFPL89PxQoMqiFjrZCPZBRjHqd0MKLwcdWZCxDdcKwJKb1AcVZBh4ISPSt6lsdLtKyX9N24flelHVCle0zEpZARX3eS1gex8BZAn1i1gKjGCZAdtIbkTGdOGJHTisSmHmkIHTSPNoQhXnEcHO7HYucOByq0bCZBeO82ZAZBF9CrXzhTyWsDu9ZAzrvdQZDZD';

const PAGE_ACCESS_TOKEN =
  'EAAELyoAkOZC8BACjxMS81Bo67ZCz8CUPtrPL32GZAilzbFtSzfNAWO4mwDurFxqEZBlS46BF6B1GZBRYlPJOVCyqsba8fcmNWq8TyE7ZBcIisZA2UuDdrU2BtQtWJBDCdCaDAjgibSKBNQRk5Y14OZA1XhkKmlRan5MijqpxQVP3GZChGOU8n0fNDGwTuZC4PdKXxw1SCCQbsG8HnqdXLzgbS9';
// FB_ROUTE_CONSTANTS
const GET_PAGE_INFO = `https://graph.facebook.com/${PAGE_ID}?fields=about,name,cover&auth&access_token=${AUTH_TOKEN}`;
const GET_FB_EVENTS = `https://graph.facebook.com/v3.2/${PAGE_ID}/events?fields=cover,name,start_time&access_token=${AUTH_TOKEN}`;

module.exports = {
  GET_PAGE_INFO,
  GET_FB_EVENTS,
  PAGE_ID,
  AUTH_TOKEN,
  PAGE_ACCESS_TOKEN,
};
